### ISSUE TITLE
please update readme, it looks weird at the moment

### ISSUE THREAD

**Issue by tallinn-learning** [Seraphim97/HomeWork8#4]
https://github.com/Seraphim97/HomeWork8/blob/795b66581ef96b524c4eebcf1cc9d28ee13dd18d/src/test/java/org/example/Solvertest.java#L7

**Comment by Seraphim97** [comment]
i don't know how to fix readme on the main page, because when i click on the pencil in the right corner, or in Idea, it looks like normal.

**Comment by tallinn-learning** [comment]
try to compare your version with this one
https://github.com/NadiaJoy/Learning-homework8
